mystr="Yudhi is going to do great"
# print(len(mystr))
# print(mystr[0:26])
# print(mystr[::-2])
# print(mystr.isalnum())
# print(mystr.isalpha())
# print(mystr.endswith("great"))
# print(mystr.count("o"))
# print(mystr.capitalize())
# print(mystr.find("is"))
# print(mystr.lower())
# print(mystr.upper())
# print(mystr.replace("is","are"))
print(mystr.center(50,"A"))